# Generated by Django 3.1.2 on 2020-11-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomName', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=30)),
                ('minDailyHoursClass', models.IntegerField(default=1)),
                ('maxDailyHoursClass', models.IntegerField(default=1)),
                ('classroom', models.ManyToManyField(to='scheduler.Classroom')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=30)),
                ('classrooms', models.ManyToManyField(to='scheduler.Classroom')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='PlansPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userData', models.CharField(default=' ', max_length=60)),
                ('planName', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'plansPermission',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeWindow', models.IntegerField()),
                ('day', models.CharField(default='', max_length=60)),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.planspermission')),
            ],
            options={
                'db_table': 'time',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('classroom', models.ManyToManyField(to='scheduler.Classroom')),
                ('lesson', models.ManyToManyField(to='scheduler.Lesson')),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.planspermission')),
                ('time', models.ManyToManyField(to='scheduler.Time')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='planId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.planspermission'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.ManyToManyField(to='scheduler.Time'),
        ),
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonAmount', models.IntegerField(default=1)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scheduler.group')),
                ('lesson', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scheduler.lesson')),
            ],
            options={
                'db_table': 'group_lesson',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='lesson',
            field=models.ManyToManyField(blank=True, through='scheduler.GroupLesson', to='scheduler.Lesson'),
        ),
        migrations.AddField(
            model_name='group',
            name='planId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.planspermission'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.ManyToManyField(to='scheduler.Time'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='planId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.planspermission'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='time',
            field=models.ManyToManyField(to='scheduler.Time'),
        ),
    ]
