# Generated by Django 3.1.2 on 2020-11-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomId', models.IntegerField()),
                ('classroomName', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='ClassroomTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomId', models.IntegerField()),
                ('timeId', models.IntegerField()),
            ],
            options={
                'db_table': 'classroomTime',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('groupName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='GroupClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('classroomId', models.IntegerField()),
            ],
            options={
                'db_table': 'groupClassroom',
            },
        ),
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('lessonId', models.IntegerField()),
            ],
            options={
                'db_table': 'groupLesson',
            },
        ),
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('teacherId', models.IntegerField()),
            ],
            options={
                'db_table': 'groupTeacher',
            },
        ),
        migrations.CreateModel(
            name='GroupTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('timeId', models.IntegerField()),
            ],
            options={
                'db_table': 'groupTime',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.IntegerField()),
                ('lessonName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.IntegerField()),
                ('classroomId', models.IntegerField()),
            ],
            options={
                'db_table': 'lessonClassroom',
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.IntegerField()),
                ('timeId', models.IntegerField()),
            ],
            options={
                'db_table': 'lessonTime',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('classroomId', models.IntegerField()),
            ],
            options={
                'db_table': 'teacherClassroom',
            },
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('lessonId', models.IntegerField()),
            ],
            options={
                'db_table': 'teacherLesson',
            },
        ),
        migrations.CreateModel(
            name='TeacherTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('timeId', models.IntegerField()),
            ],
            options={
                'db_table': 'teacherTime',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeId', models.IntegerField()),
                ('timeWindow', models.IntegerField()),
            ],
            options={
                'db_table': 'time',
            },
        ),
    ]
