# Generated by Django 3.1.2 on 2020-11-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classroomId',
        ),
        migrations.RemoveField(
            model_name='group',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lessonId',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacherId',
        ),
        migrations.RemoveField(
            model_name='time',
            name='timeId',
        ),
    ]
