# Generated by Django 3.1.2 on 2020-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='maxDailyHours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='teacher',
            name='maxWeeklyHours',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='minDailyHours',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='minWeeklyHours',
            field=models.IntegerField(default=10),
        ),
    ]
