# Generated by Django 3.1.2 on 2020-11-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planspermission',
            name='userNumber',
            field=models.CharField(max_length=60),
        ),
    ]
