# Generated by Django 3.1.2 on 2020-11-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20201109_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
